Added vg roles
gluster/gdeploy pull request #419
Opened 2017-08-10 07:56 UTC by ashmitha7

2017-08-18 08:16 UTC, sabose requested changes
Is the corresppnding vg.py already checked in?

Please update description in commit.

2017-08-18 08:16 UTC, sabose commented on examples/role-playbook/vg/vgconvert.retry
> +10.70.42.89
I think this file is not needed in commit?

2017-08-18 08:16 UTC, sabose commented on examples/role-playbook/vg/vgextend.retry
> +10.70.42.89
File not needed?

2017-08-18 08:16 UTC, sabose commented on roles/vg/vgconvert/tests/test.yml
> +---
How are these tests run? Do we have a CI in place to run the tests?

2017-08-18 08:16 UTC, sabose commented on roles/vg/vgcreate/README.md
> +disk: disk or partition on which the pv is created.
Can I specify multiple disks here? For example: /dev/sdb,/dev/sdc?

2017-08-21 06:23 UTC, ashmitha7 commented on examples/role-playbook/vg/vgconvert.retry
> +10.70.42.89
Yes, .retry extension files are automatically generated. I missed deleting this. I'll add it to gitignore to avoid future problems.

2017-08-21 06:24 UTC, ashmitha7 commented on roles/vg/vgcreate/README.md
> +disk: disk or partition on which the pv is created.
Yes, I'll give it a try with 3 disks just to be sure. Spoken to Sac about this too.

2017-08-21 06:25 UTC, ashmitha7 commented on examples/role-playbook/vg/vgextend.retry
> +10.70.42.89
Will have to delete this from the commit.

2017-08-22 06:26 UTC, sac commented
Can you abandon this. Remove the .retry files and resend the PR?

2017-08-22 06:32 UTC, ashmitha7 commented
Yes, okay.

2017-08-22 08:07 UTC, closed without merging