Fixes BZ #1515733: Do not pick hostnames if ctdb_nodes not set.
gluster/gdeploy pull request #471
Opened 2017-12-18 11:58 UTC by devyanikota

When ctdb_nodes are not set, default behaviour of gdeploy is to
pick up hosts from the host list.
gdeploy should throw error when hostnames are given instead of IPs.

BZ URL: https://bugzilla.redhat.com/show_bug.cgi?id=1515733
Signed-off-by: Devyani Kota <devyanikota@gmail.com>

2017-12-18 12:20 UTC, sac requested changes
Other than the mentioned changes. Looks good otherwise. Could you test as well please?

2017-12-18 12:20 UTC, sac commented on gdeployfeatures/ctdb/ctdb.py
> +            if s.isalpha() is True:
if s.isalpha():
     ...

should be enough. 

Instead of `s' why not say for host in Global.hosts ... more readable. What does s stand for?

2017-12-18 12:20 UTC, sac commented on gdeployfeatures/ctdb/ctdb.py
> +                msg = "Need ips for nodes, found hostnames."
This message is quite misleading. Say:

Provide ip address in [hosts] section or define ctdb_nodes variable with ip addresses.

2017-12-18 13:29 UTC, devyanikota commented
@sac tested with the following conf file[1], works fine for me. Please check.

> [devyani@localhost cnfg]$ gdeploy -c ctdb-setup.conf 
Provide ip address in [hosts] section or define ctdb_nodes variable with ip addresses.

[1] https://paste.opensuse.org/77090900
Thank you.

2017-12-20 10:33 UTC, sac approved these changes

2017-12-20 10:33 UTC, merged