handles vdo volume reboot
gluster/gdeploy pull request #511
Opened 2018-05-09 09:34 UTC by ramkrsna

- x-systemd.requires=vdo.service 
- handles reboot scenarios for vdo volumes

2018-05-11 01:42 UTC, sac approved these changes
Looks good to me. Have you completed this checklist:

* Tested for both VDO and non-vdo devices?
* Check fstab entries for VDO devices
* Check fstab entries for non-VDO devices
* Reboot checks:
   - Should start vdo service and mount vdo devices
   - Should mount non-vdo devices
   - Should not panic due to wrong fstab entries.

@ramkrsna if the above tests are done okay to merge.
@devyanikota request to review once.

2018-05-18 06:57 UTC, devyanikota reviewed
Hi, I have reviewed the patch. +1, looks good to me.
@ramkrsna have you tested the scenarios mentioned by sachi?

2018-05-22 08:07 UTC, sac requested changes

2018-05-22 08:07 UTC, sac commented on playbooks/mount.yml
> +    opts="inode64,noatime,nodiratime"
This would cause an error. s/=/:/

2018-05-22 08:07 UTC, sac commented on playbooks/mount.yml
> +      opts="{{opts}},"+"x-systemd.requires=vdo.service"
s/"+"//

2018-05-22 08:37 UTC, sac commented
Closing this, will submit a new patch. The above errors cause boot hang.

2018-05-22 08:37 UTC, closed without merging